# Generated by Django 5.2.14 on 2026-05-09 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('full', '全面分析'), ('technical', '技术面'), ('regime', '市场状态'), ('risk', '风险评估')], default='full', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('metrics_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_center.symbol')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
