# Generated by Django 5.2.14 on 2026-05-09 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_center', '0001_initial'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_cash', models.FloatField(default=100000)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('equity_curve', models.JSONField(blank=True, default=list)),
                ('trades_json', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('done', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_center.symbol')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
