# Generated by Django 5.2.14 on 2026-05-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('strategy_type', models.CharField(choices=[('ma_cross', '双均线交叉'), ('momentum', '动量策略'), ('mean_reversion', '均值回归'), ('grid', '网格交易'), ('custom', '自定义')], default='ma_cross', max_length=50)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('code', models.TextField(blank=True, help_text='自定义策略Python代码')),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
